if(GetLocale() ~= 'zhTW') then return end

local _, core = ...
local baseLocale = {
    ["Main"] = "般",
    ["Battle for Azeroth"] = "決戰艾澤拉斯",
    ["Legion"] = "軍臨天下",
    ["Warlords of Draenor"] = "德拉諾之霸",
    ["Mists of Pandaria"] = "潘達利亞之謎",
    ["Cataclysm"] = "浩劫與重生",
    ["Wrath of the Lich King"] = "巫妖王之怒",
    ["Currently Tracking:"] = "目前追蹤:",
    ["Achievements"] = "成就",
    ["Achievement"] = "成就",
    ["Tactics"] = "戰術",
    ["Features:"] = "功能:",
    ["- Tracks when the criteria of instance achievements have been met and output this to chat"] = "- 追蹤達到成就的要求時輸出到聊天視窗",
    ["- Tracks when the criteria of instance achievements has been failed and outputs this to chat"] = "- 追蹤成就的要求失敗時輸出到聊天視窗",
    ["- Keeps track of achievements which require you to kill so many mobs within a certain time period. It will announce to chat when enough mobs have spawned and whether they were killed in the time period."] = "- 持續追蹤成就要求你在指定時間內擊殺多少怪物。會在聊天視窗通報已經擊殺足夠數量的怪物以及是否在時間內完成。",
    ["- Scans all players in the group to see which achievements each player is missing for the current instance"] = "- 掃描隊伍中的所有玩家，檢查每個玩家缺少當前副本的哪個成就。",
    ["- Announce to chat players who are missing achievements for certain bosses"] = "- 在聊天視窗通報哪個玩家缺少哪個首領的成就",
    ["- Announce to chat tactics for a certain boss"] = "- s在聊天視窗通報某些首領的成就解法",
    ["Options:"] = "選項:",
    ["Enable Addon"] = "啟用插件",
    ["Show Minimap Button"] = "掃描仍在進行中",
    ["(Achievement Tracking Disabled)"] = "(成就追蹤已停用)",
    ["Enter instance to start scanning"] = "(進入副本開始掃描)",
    ["Output Tactics"] = "輸出戰術",
    ["Output Players"] = "輸出玩家",
    ["Track"] = "追蹤",
    ["Players"] = "玩家",
    ["No players in the group need this achievement"] = "隊伍中沒有玩家需要做這個成就",
    ["scan still in progress"] = "掃描仍在進行中",
    ["Enter instance to start scanning"] = "進入副本開始掃描",
    ["Players who need Achievement"] = "需要做成就的玩家",
    ["Disabled"] = "已停用",
    ["Enabled"] = "已啟用",
    ["Tracking"] = "正在追蹤",

    -- ["Starting Achievement Scan For"] = "Starting Achievement Scan For",
    -- ["This may freeze your game for a few seconds"] = "This may freeze your game for a few seconds",
    -- ["Achievement Scanning Finished"] = "Achievement Scanning Finished",
    -- ["Do you want to enable achievement tracking for"] = "Do you want to enable achievement tracking for",
    -- ["Track Achievements"] = "Track Achievements",
    -- ["Yes"] = "Yes",
    -- ["No"] = "No",
    -- ["Achievement Tracking Enabled for"] = "Achievement Tracking Enabled for",
    -- ["List of slash commands"] = "List of slash commands",
    -- ["help"] = "help",
    -- ["enable"] = "enable",
    -- ["shows a list of avaliable slash commands"] = "shows a list of avaliable slash commands",
    -- ["enable/disable IAT achievement tracking"] = "enable/disable IAT achievement tracking",
    -- ["Other"] = "Other",
    -- s["Only track missing achievements"] = "Only track missing achievements",
}

core:RegisterLocale('zhTW', baseLocale)
